### ISSUE TITLE
Message > Some react icons cannot display 

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#105]
# Actual Result
Some react icons cannot display on the app (I cannot try with all icons, sorry :'( )
On Mobile:
![image](https://user-images.githubusercontent.com/69950655/102439753-6b338800-4051-11eb-97a5-ca7dc89f351a.png)

On Web:
![image](https://user-images.githubusercontent.com/69950655/102438768-869d9380-404f-11eb-8ae3-f5f35f88a4a7.png)

# Expected Result
All react icons should display normally

**Comment by bobs4462** [comment]
Fixed the issue with null and question marks. But still some issue remains. It's that web version of Twake supports very limited range of emojis, it supports only standard tone variations for some emojis to be precise. So for now you cannot pick emojis with dark tones for example.

**Comment by RomaricMourgues** [comment]
We can move this issue to Twake repo, I will see with my team what we can do :)

**Comment by tlle14** [comment]
Thank @bobs4462 
The icon is displayed correctly on both web and mobile version:
![image](https://user-images.githubusercontent.com/69950655/103118082-e7f0e280-469f-11eb-9194-f1eb8e3ee010.png)
![image](https://user-images.githubusercontent.com/69950655/103118098-f63efe80-469f-11eb-8078-d67d7b3748ef.png)
