### ISSUE TITLE
iOS > The app name is displaying all lowercase letters

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#109]
# Actual Result
On iOS device, the app name is `twake`
![image](https://user-images.githubusercontent.com/69950655/102572289-3a6d5480-411e-11eb-8fc2-e821bb5137f2.png)

# Expected Result
It should display `Twake`

# Environment
iOS devices

**Comment by romanesko** [comment]
fixed in 1.3 (4)

**Comment by tlle14** [comment]
Thank @romanesko 
Retest pass!
![image](https://user-images.githubusercontent.com/69950655/103118318-ec69cb00-46a0-11eb-919f-03453012f780.png)
