### ISSUE TITLE
iOS > Cannot close the keyboard when opening the chat

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#110]
# Actual Result
When opening a chat, tap to reply textbox, it displays a keyboard. But user cannot close the keyboard.
On Android, there's a system button to close the keyboard, but on iOS we don't have any.
https://streamable.com/2kgufy

# Expected Result
The user should be able to close the keyboard by tapping the area around it.

# Environment
All iOS devices

**Comment by romanesko** [comment]
fixed in 1.3 (4)

**Comment by tlle14** [comment]
Thank @romanesko 
Retest pass!

https://user-images.githubusercontent.com/69950655/103060145-c299a100-45d9-11eb-9849-3e9a4f5d4009.mp4
