### ISSUE TITLE
Thread > Improve the displaying of parent message and the responses

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#112]
# Actual Result
When opening the keyboard, the text area becomes untidy. There're too many parts on a screen.
- The response counter takes a fixed area that is not worthy
- The parent message has a special format cannot display well on the Thread screen.
![image](https://user-images.githubusercontent.com/69950655/102575174-2f69f280-4125-11eb-8235-b492f60462ac.png)

# Expected Result
Please work with our designer. 
This is my suggestion: In a thread screen, the parent message should display fully, followed by the response counter, then the responses as in the old Twake app on iOS.
https://streamable.com/jtangf

# Environment
app-release[2020-12-17]

**Comment by BastiaanVanGaalen** [comment]
@tlle14 This UX bug will be re-engineered in a new app.

**Comment by bobs4462** [comment]
@tlle14 I think we can close this issue, it can be reopened if new design will have the same issue.

**Comment by tlle14** [comment]
It's sure, retest pass!
Thank @bobs4462
