### ISSUE TITLE
Vietnamese language displays in error font on Mobile

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#113]
# Actual Result
Some Vietnamese character displays in an error font
![image](https://user-images.githubusercontent.com/69950655/102586112-1f114200-413c-11eb-8c69-2dbb1e8ee5c9.png)

# Expected Result
The font should be corrected

# Environment
All mobile devices

**Comment by romanesko** [comment]
<img src="https://www.fresher.ru/wp-content/uploads/2018/04/142.jpg" width="400">

**Comment by romanesko** [comment]
We are using default fonts for both platforms. I have no idea how to solve this for now (

**Comment by tlle14** [comment]
Maybe the ugly font makes me think it was an error.
Please leave it to the postponed column and review later

**Comment by tlle14** [comment]
Thank @romanesko 
Retest pass 

![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/f9e5c849-8d70-43c4-83c8-22fdd7d59170)
