### ISSUE TITLE
Cannot submit/react a message

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#116]
# Actual Result
The message doesn't display after submitted
https://streamable.com/ad3sh0
https://jmp.sh/PkA8pM6

# Expected result
It should be able to send a message

# Environment
All mobile devices
app-release[2020-12-17]

**Comment by romanesko** [comment]
Could you upload to jumpshare.com?

**Comment by tlle14** [comment]
> Could you upload to jumpshare.com?

updated

**Comment by romanesko** [comment]
fixed

**Comment by tlle14** [comment]
Thank @romanesko 
Retest pass!
