### ISSUE TITLE
Channel/Direct has a grey  block around the date 

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#118]
# Actual Result
There is a gray block at the top of the messages list, under the channel name.
![image](https://user-images.githubusercontent.com/69950655/102608499-8d65fc80-415c-11eb-93b8-7388a0bc582e.png)

# Expected Result
The block should have the same color as the background.
The block should display in ombre style like this:
![image](https://user-images.githubusercontent.com/69950655/102609472-20ebfd00-415e-11eb-976a-61bca80ab34b.png)

# Environment
All mobile devices

**Comment by BastiaanVanGaalen** [comment]
@tlle14 Can you explain why would we need to change the style of this block to gradient pink?

**Comment by tlle14** [comment]
> @tlle14 Can you explain why would we need to change the style of this block to gradient pink?

Hi @BastiaanVanGaalen , it just an example of a gradient, not the exact color. Please get help from our designer.

**Comment by tlle14** [comment]
Thank @RockinPaul and @bobs4462 
Retest pass
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/e94741be-e1cc-473d-9f1a-004ecd5cc447)
