### ISSUE TITLE
Date label is hidden

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#124]
# Actual Result
Text label is hidden as in this image
![image](https://user-images.githubusercontent.com/69950655/103119944-3b672e80-46a8-11eb-8a33-fe821b90f643.png)

# Expected Result
It shouldn't be hidden

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 No matter what, this particular  timestamp text label can be displayed in a one line, no line breaks and multiple lines are allowed. *)

**Comment by tlle14** [comment]
Thank @RockinPaul and @bobs4462 
Retest pass!
The month name has been shortened
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/382b7cfe-ef86-47c5-b506-cb759b1d5f4f)
