### ISSUE TITLE
Some texts are bold 

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#125]
# Actual Result
Channel name, button name (Reply/delete/copy) and placeholder text (`reply`) are bold.
![image](https://user-images.githubusercontent.com/69950655/103127794-87749c00-46c5-11eb-9da7-bfaf63e6e658.png)
![image](https://user-images.githubusercontent.com/69950655/103127774-79bf1680-46c5-11eb-85b3-0f1a6627c19f.png)
![image](https://user-images.githubusercontent.com/69950655/103127810-95c2b800-46c5-11eb-8d5e-ab6560c4a9d6.png)

# Expected Result
Please confirm if this is designed or an issue.
Texts should be lighter for a better UI. 

# Environment
Both ios and android device

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 
Channel name: medium font-weight (font-weight)
Text of the label on ActionSheet: regular (font-weight)
Placeholder label: regular (font-weight) + alpha (opacity) 0.6

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!

- Channel name:
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/085bf4c2-777a-47eb-90ab-44e5c701858e)

- Text of the label on ActionSheet
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/7779dc20-1291-478e-b0ea-60ddbd834244)

- Placeholder 
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/f55a3086-43fa-4c80-b1e4-3e45d11769f6)
