### ISSUE TITLE
Workspaces list is displaying partially on the sidebar menu

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#126]
# Actual Result
Workspaces list is displaying partially on the sidebar menu:

https://user-images.githubusercontent.com/69950655/103132856-76358a80-46d9-11eb-8d83-4af5bee3802e.mp4
![image](https://user-images.githubusercontent.com/69950655/103132788-fc050600-46d8-11eb-81f0-1fbbd0bb1a00.png)

# Expected Result
The list should display fully on the sidebar

# Environment
Both ios and android

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 https://zpl.io/bAeywAe
As can be concluded from the screen ListView widget spans till the bottom border of Main view and goes under fixed cell on the bottom

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass
https://images.zenhubusercontent.com/309637937/fd6c182b-48a6-4a4f-b89d-4e919ec2d78a/videob60c899d_b3c4_4204_ad64_45d2229692b5video.mp4
