### ISSUE TITLE
A long workspace name will be hidden on the channel list screen

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#127]
# Actual Result
The workspace name is hidden on the narrow screen
![image](https://user-images.githubusercontent.com/69950655/103133256-fbba3a00-46db-11eb-9a9d-ae7e52354532.png)

# Expected Result
The workspace name should be shown entirely

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 This issue was discussed and further resolved in a different chat.
Channel name has a char count limit and when exceeded three dots show up.

**Comment by tlle14** [comment]
Hi @RockinPaul @bobs4462 

The long channel name should be displayed with three dots [...] as @BastiaanVanGaalen comment above. 
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/561fd11e-4653-409b-8d4b-020e8e48a3f2)

Please fix to follow our design. 
Thank you

**Comment by tlle14** [comment]
Thank @RockinPaul 
Retest pass
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/d8125d48-aca2-4db6-9549-4ba82d91312f)
