### ISSUE TITLE
A direct chat with a person always displays all participant names

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#132]
# Actual Result
 A direct chat with a person always displays all participant names
![image](https://user-images.githubusercontent.com/69950655/103255999-277c3f00-49be-11eb-867d-a9c4faaa0ed8.png)
![image](https://user-images.githubusercontent.com/69950655/103256063-5db9be80-49be-11eb-96ea-020ba68c7cba.png)

# Expected Result
Should display the name of the guest only

# Environment
Both Android and iOS

**Comment by bobs4462** [comment]
Was fixed on proxy, the issue shouldn't be there anymore

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/2ecd12d7-1810-4aec-bd51-a044a2084d1f)

**Comment by tlle14** [comment]
It seems the issue relates to the server @bobs4462 
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/ea622205-55ea-4756-875a-4fbac3ddc5ca)

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/514f86ec-6e39-4a69-94aa-881c9e202764)
