### ISSUE TITLE
Cannot scroll an expanded parent message in a thread

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#133]
# Precondition
A long message (>300 characters) with the responses

# Actual Result
A thread with a long parent message doesn't have a scroll after expanding
https://user-images.githubusercontent.com/69950655/103263562-cadb4d00-49da-11eb-8ed9-3c3cf0070613.mp4

# Expected Result
After expanding, a thread should have scroll

# Environment
Both ios and android app

**Comment by bobs4462** [comment]
That's a strange bug, I'll try to hotfix it, or if not, the issue should be gone in new design

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass
https://images.zenhubusercontent.com/309637937/e80f3b75-b79b-4b3d-a542-a5b46e256168/video8f782968_9b5b_4e87_95d1_25b375a5a09cvideo.mp4
