### ISSUE TITLE
The app displays 2 times loading when starting app

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#134]
# Actual Result
When opening the app, it has 2 times loading before display a channel list.
https://user-images.githubusercontent.com/69950655/103269618-c87fef80-49e8-11eb-8cc2-c97b955eadec.mp4

# Expected Result
It should have 1 time loading before display a channel list

# Environment
Both Android and ios app

**Comment by bobs4462** [comment]
Fixing it during refactoring.

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!
https://images.zenhubusercontent.com/309637937/b15d13ff-adfa-42ed-851f-fd67dd2d340e/20210118_102140.mp4
