### ISSUE TITLE
A self direct chat cannot display on Mobile 

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#135]
# Precondition
On Web, a user sends a direct chat to himself 

# Actual Result
The self-direct chat cannot display on Mobile
On Web:
![image](https://user-images.githubusercontent.com/69950655/103271103-dedb7a80-49eb-11eb-8aa3-1f86ed18d16b.png)

On Mobile:
![image](https://user-images.githubusercontent.com/69950655/103271139-02062a00-49ec-11eb-840b-315f56a0e288.png)

# Expected Result
The self-direct chat should be displayed on Mobile

# Environment
Both Android and iOS

**Comment by bobs4462** [comment]
Seems that proxy doesn't recognize this kind of directs. Will investigate

**Comment by bobs4462** [comment]
@romanesko the issue still persists in new api, we are still not receiving direct messages with self

**Comment by romanesko** [comment]
fixed

**Comment by hieuhoang998** [comment]
Hi, This issue is fixed, so I close this.
Thank you.
