### ISSUE TITLE
Cannot access Test company 

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#136]
# Actual Result
Cannot access 2 test companies on Mobile. They display 0 workspaces. While on Web they still display the workspace list.
![image](https://user-images.githubusercontent.com/69950655/103273449-eaca3b00-49f1-11eb-956f-632b098defc4.png)

# Expected Result
Please check the test data. The workspace list should display on Mobile

# Environment
Both Android and iOS devices

**Comment by bobs4462** [comment]
Might be the proxy caching issue, @romanesko will investigate

**Comment by bobs4462** [comment]
@tlle14 Romaric said, that it won't be possible to have empty companies, so the issue should not ever occur in newer versions

**Comment by tlle14** [comment]
I agree. Currently, when creating a company, there will have a default Workspace
