### ISSUE TITLE
Display an empty sidebar when having no workspace in the company

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#137]
# Precondition
A company have no workspace

# Actual Result
When tapping on the company, it seems cannot open.
But when reopen the menu sidebar, it displays an empty sidebar (no workspace)
https://user-images.githubusercontent.com/69950655/103276138-531c1b00-49f8-11eb-84e7-1724fa29c359.mp4

# Expected Result
Please discuss more with our BA about this behavior. 
- If the empty company is selectable, it should display the empty channel list.
- If the empty company is unselectable, it shouldn't show the empty sidebar. 

# Environment
Both android and ios devices

**Comment by bobs4462** [comment]
Yes, that's one of the edge cases. I'll take into account during refactor, and probably we might be able to fix it.

**Comment by bobs4462** [comment]
@RomaricMourgues can you please, clarify, will it be possible to create a company without single workspace?

**Comment by RomaricMourgues** [comment]
No this is not possible

**Comment by bobs4462** [comment]
Great! One more thing, is it possible for the user to be a member of multiple companies, with the ability to change between them like in old version of twake?

**Comment by RomaricMourgues** [comment]
Yes it will still be possible, but should be a small option, main feature is to change workspace :)

**Comment by bobs4462** [comment]
@tlle14, I don't see any point in keeping this issue around, as it seems impossible to create a company with no workspaces and having multiple companies should be a rare thing.

**Comment by tlle14** [comment]
I've been updated the business. When creating a company, there will have a default workspace, that why this issue will never happen. 
Thank @RomaricMourgues and @bobs4462
