### ISSUE TITLE
Time format is not consistent between screens

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#139]
# Actual Result
The channel/direct list screen displays 2 time formats: 12 hours and 24 hours
![image](https://user-images.githubusercontent.com/69950655/103329202-4ea24180-4a8e-11eb-8c64-fa333363b299.png)

# Expected Result
It should display 1 type of time format in the app.

# Environment
Both Android and iOS

**Comment by bobs4462** [comment]
I agree, it should be consistent everywhere, will discuss the issue with the Designer

**Comment by BastiaanVanGaalen** [comment]
In my view, it should b more natural, somewhat people have gotten used to such as:  **12 Aug, 13:30** rather than **12/08 13:30**

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass

On Channel list:
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/e785331b-dddc-47e2-9462-181efd03508c)

On details chat:
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/40ae98d8-a799-4a1c-8112-906b138fac76)
