### ISSUE TITLE
Emoticon keyboard blinks each time selecting a emoticon

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#140]
# Actual Result 
Open the emoticon keyboard, it blinks each time user select an emoticon
https://user-images.githubusercontent.com/69950655/103329703-88744780-4a90-11eb-98d9-addc85f63193.mp4

# Expected Result
The emoticon keyboard shouldn't blink when selecting an emoticon

# Environment
Both Android and iOS

**Comment by bobs4462** [comment]
Will work on a custom emoji keyboard soon, for now we'll probably remove emoji keyboard at all.
