### ISSUE TITLE
When loading chat history, it should have a loading icon 

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#141]
# Actual Result
When loading a chat history, it doesn't have a loading icon, makes the user doesn't know if the chat is continue loading or not
https://user-images.githubusercontent.com/69950655/103330545-8d3afa80-4a94-11eb-9338-f9b47f837cf3.mp4

# Expected Result
When scrolling down to load the chat history, the app should display a loading icon 

# Environment
Both Android and iOS

**Comment by bobs4462** [comment]
Yes, good point! I'll work on this issue as soon as I finish refactoring

**Comment by tlle14** [comment]
Hi @bobs4462 
Retest failed

It displays a blank page when loading a chat history
Please fix
https://images.zenhubusercontent.com/309637937/0779ea03-d424-4cdf-8d79-d3ae3b5be02d/videofd082f69_3018_410e_9fc3_194df375d3a1video.mp4

**Comment by tlle14** [comment]
Hi @bobs4462 
The issue above is no longer existing. 
But tapping `See all answers` while loading chat history will open an empty screen
https://images.zenhubusercontent.com/309637937/04e3b48a-410b-46d3-b431-9c049aacea05/video9e577669_1fd0_4ef1_90a0_662c087177f8video.mp4

**Comment by bobs4462** [comment]
It took me a while to catch this bug (with throttling internet connection), but this bug is no more :)

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!
https://images.zenhubusercontent.com/309637937/a57ca092-532b-47a1-aef0-9dedb78f7a1a/videoddc31728_5e12_497d_b68f_38365e0674b5video.mp4
