### ISSUE TITLE
The app doesn't display a current line when using app emoticon keyboard

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#143]
# Actual Result
The chatbox is able to display maximum 4 lines.
When using a device keyboard, it always displays a current line while typing.
But when using an App keyboard (emoticon keyboard), it cannot display a current line while selecting emoticons

https://user-images.githubusercontent.com/69950655/103338297-828e5e80-4ab0-11eb-852f-5fee45567fff.mp4

# Expected Result
The app should display a current line while using the app emoticon keyboard

# Environment
Both Android and iOS

**Comment by bobs4462** [comment]
We are considering of removing emoji keyboard for now, and may be will implement a custom one in future.
Let's keep the issue around for now.

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass
https://images.zenhubusercontent.com/309637937/658d4301-4e14-4e03-9267-606205d20f7e/videoe876f17b_b102_47c0_bcc2_2a0085787b0fvideo.mp4
