### ISSUE TITLE
Mention button doesn't work

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#145]
# Actual Result
The button doesn't work
![image](https://user-images.githubusercontent.com/69950655/103342496-2df0e080-4abc-11eb-98fb-241f0fd4a662.png)

# Expected Result
Please confirm if this feature is for Version 1 or not. If not, we should keep this ticket for tracking purpose. 

Thanks!

**Comment by bobs4462** [comment]
We are going to remove this thing and use @ symbol from keyboard as trigger to select users in future version
