### ISSUE TITLE
Handle RangeError when channels are empty.

### ISSUE THREAD

**Issue by RockinPaul** [TwakeApp/Mobile#165]
![photo_2021-01-12 11.45.05.jpeg](https://images.zenhubusercontent.com/5ffc24a2a62ff7cf134e10b3/d34a7b55-179b-4bcf-8266-cd7ab13a5f65)

**Comment by tlle14** [comment]
Hi @bobs4462 I cannot retest this issue. 
But as I understand, a channel always contains at least a creator, that why it can never be empty.
