### ISSUE TITLE
Add support for direct channel creation from the application

### ISSUE THREAD

**Issue by bobs4462** [TwakeApp/Mobile#168]

**Comment by bobs4462** [comment]
The api endpoint for creating a channel is **POST /channels**

**required fields in request body:**
  - company_id: str
  - workspace_id: str
  - name: str 
  - visibility: str  <'public' | 'private' | 'direct'>

**optional fields in request body:**
  - icon: str
  - description: str
  - channel_group: str
  - default: bool (if true — add every workspace member to the channel, only available for public channels)
  - members: str[] — list of user ids  (direct only)

**Comment by tlle14** [comment]
Hi @bobs4462 @RockinPaul 
I cannot verify this ticket.

**Comment by tlle14** [comment]
The adding direct screen is similar to adding channel screen. 
I don't think it's accurate. 
Please rework.
