### ISSUE TITLE
Login > The login screen displays a bad UI

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#178]
# Actual Result
 Login screen responsive with the inappropriate line breaks
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/a9414051-4b2d-4905-bc03-330a2d031bed)

# Expected Result
The login screen should responsive gracefully on the Mobile App. 
Please see the screen on Chrome browser
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/a174105c-0804-43ac-90fe-91a7c43b9a50)

# Environment
Samsung Mobile 6.5inch
Build version: twake.2.1.0

**Comment by hieuhoang998** [comment]
Hi, This issue is fixed, so I close this.
Thank you
