### ISSUE TITLE
Create Channel > UI improvement

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#181]
# Actual Result
1. Texts on the New Channel screen are bold.
=> The placeholders and textbox descriptions should display regular texts

2. User need to tap to the background to close the New Channel screen
=> There should have `Cancel` button

3. The textbox descriptions have inappropriate break line
=> Text should stay in one line.

![image](https://user-images.githubusercontent.com/69950655/104988982-07372180-5a4c-11eb-93a9-748353c85262.png)

# Expected Result
Please get help from our designer and BA to have a better UI

# Environment
Samsung Mobile
Build version: twake.2.1.0

**Comment by BastiaanVanGaalen** [comment]
@tlle14 
@RockinPaul 
1. agreed
2. i will add a "close" icon on the left side of modalView navBar
3. sure, they must be in one line

**Comment by BastiaanVanGaalen** [comment]
@RockinPaul  Channel creation flow has been updated, i added "Cancel" button on the first screen:
https://zpl.io/VQl3o95

**Comment by tlle14** [comment]
Thank @BastiaanVanGaalen and @RockinPaul 
Retest pass
https://images.zenhubusercontent.com/309637937/895a01c5-0a7c-4075-9129-9ce063aeb5dc/video506ba533_ad59_4b8d_a967_662bab02f750video.mp4
