### ISSUE TITLE
Create Channel > Able to create the channels with the same name

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#185]
# Actual Result
Recently, we are able to create multiple channels with the same name
https://user-images.githubusercontent.com/69950655/105004031-fd221c80-5a65-11eb-8018-bdc732721538.mp4

# Expected Result
Please confirm if this is expected behavior?
Many channels might be accidently created at a time when double taps on the `create` button

**Comment by RockinPaul** [comment]
Yes, possible name duplication is expected behavior. 
However, the issue that allows multiple taps on create button will be resolved in the next build.

**Comment by tlle14** [comment]
Thank @RockinPaul 
Retest pass

https://images.zenhubusercontent.com/309637937/e98182c6-69d1-48cf-a58-0c542f08a2d2/video197cf86d_9a77_4d3f_9d5d_0e8633ca2785video.mp4
