### ISSUE TITLE
Create Channel > Deleted channels appear when reopen the app

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#187]
# Precondition
The channel is deleted on Web App 

# Actual Result
When reopening the mobile app, the deleted channels appear. 
The user needs to refresh the app to make the channels disappear.

# Expected Result
The mobile app should update the latest state

# Environment
Android mobile
Version: twake.2.1.0

**Comment by bobs4462** [comment]
We currently have no way to force update in application. The only solution is to periodically pull the fresh data from server.
I'll work on that, when I have time.

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!
https://images.zenhubusercontent.com/309637937/0f78bba2-35f3-4e42-aabc-96fcd81d8005/videoaea34d73_35ce_4188_bd03_6760974a6f91video.mp4
