### ISSUE TITLE
Create Channel > 2 creation screens should optimized to 1 screen

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#190]
# Actual Result
We need to fill 2 screens to create a channel
![image](https://user-images.githubusercontent.com/69950655/105026221-e76e2080-5a80-11eb-9fee-d7c36eb06aaa.png)

![image](https://user-images.githubusercontent.com/69950655/105026171-d9200480-5a80-11eb-8766-2c456a508feb.png)

# Expected Result
I suggest creating a channel by 1 screen. Why don't we combine 2 screens into 1?
Please confirm with our BA, PO, and Designer.

# Environment
Android App
Build version: twake.2.1.0

**Comment by BastiaanVanGaalen** [comment]
@tlle14 As keyboard shows up for users to feed some input into the system, it occupies more than 1/3 of a screen's height, given the amount of small-height devices we have to avoid scrolling and any other behaviour that eats away on small devices.
We can make A/B testing with second merged-into-one-screen version and compare UX feedback.
What do u think?

**Comment by tlle14** [comment]
Hi @BastiaanVanGaalen 
Could you please discuss this with our BA and PO to have a final decision? 
I guess the scroll is okay to appear.

**Comment by BastiaanVanGaalen** [comment]
@today i will verify the UX of "separate screens" flow and provide you with a final decision on that.

**Comment by tlle14** [comment]
Thank @BastiaanVanGaalen and @RockinPaul 
Retest pass
https://images.zenhubusercontent.com/309637937/bce1b490-9623-40dc-8fa0-81397e3a13c4/video33857713_8e81_4cfe_85d5_e7b72a8e1fadvideo.mp4
