### ISSUE TITLE
Use headless inappwebview in order to use Flutter forms

### ISSUE THREAD

**Issue by bobs4462** [TwakeApp/Mobile#194]
Headless inappwebview is required so we can swap webview with native flutter forms, but still be able to communicate with twake console behind the scenes. 

The library can be accessed here https://github.com/pichillilorenzo/flutter_inappwebview

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 how is that somehow related to UI? I mean can I somehow help you with resolving or fixing it?

**Comment by bobs4462** [comment]
@BastiaanVanGaalen, it's directly related to UI, in a way that we are going to ditch webview with web forms, and use our own custom flutter forms instead, but we still need to somehow talk to auth web forms behind the scene (there's no way around). As for the help, no, it's mostly a technical issue which we can resolve ourselves, but thanks for asking :)
