### ISSUE TITLE
It is automatically login after reinstall the app

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#197]
# Actual Result
After reinstalling the app, it is automatically logged in (by data saved in the local storage?)

https://user-images.githubusercontent.com/69950655/105136819-df67bc80-5b24-11eb-8e60-44a22d7f3097.mp4

# Expected Result
It shouldn't automatically login  after reinstalling the app
 
# Steps to reproduce

1. Logout from the app 
2. Uninstall the app
3. Reinstall the app again
4. Open the app, it is automatically logged in.

# Environment
Android mobile
Build version: twake.2.1.1

**Comment by bobs4462** [comment]
Wow, that's unexpected, are you sure you logged out? Maybe it's the issues with web page which is used for login, I think we are not clearing cookies well enough. I'll try to reproduce the issue, and will get back in touch

**Comment by tlle14** [comment]
Sorry @bobs4462  for missing the evidence. I've just updated the video file. Please check

**Comment by tlle14** [comment]
@bobs4462 I cannot log in to the app using another account. I guess this issue has the same root cause as this ticket. 
Please be noted.

**Comment by bobs4462** [comment]
> @bobs4462 I cannot log in to the app using another account. I guess this issue has the same root cause as this ticket.
Please be noted.

Which account are you trying to log in with? Does it belong to any company which is created on new database?

**Comment by bobs4462** [comment]
> It shouldn't automatically login after reinstalling the app

It seems to be a very evasive bug, and we are unable to reproduce it. Can you please provide us with more data: phone model, android version?

**Comment by tlle14** [comment]
Hi @bobs4462 
I always got this issue when testing with:
- the company owner account
- on Samsung A51
- Android 10

**Comment by tlle14** [comment]
I will try with other devices.

**Comment by tlle14** [comment]
I also cannot reproduce this issue on Xiaomi Note 9.

**Comment by tlle14** [comment]
Cannot reproduce on other phones
