### ISSUE TITLE
Create Channel > Creation screen is hidden when reopening

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#198]
# Actual Result
Open a create channel screen then close it. 
When reopening the screen, it is hidden
https://user-images.githubusercontent.com/69950655/105140502-623f4600-5b2a-11eb-886c-db738a59e1de.mp4

# Expected Result
The screen should be shown normally

# Environment
Android mobile
Build version: twake.2.1.1

**Comment by tlle14** [comment]
Cannot retest because of the issue unable to open the keyboard
https://app.zenhub.com/workspaces/twakemobile-5fa5101d98879700119ccea9/issues/twakeapp/mobile/191

**Comment by hieuhoang998** [comment]
Hi, This issue is fixed, so I close this.
Thank you
