### ISSUE TITLE
Create Channel > Member is able to create a channel 

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#206]
# Precondition
The current user is a member of the company
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/5ca11907-4ded-4ef4-9901-e93c54565afb)

# Actual Result
A Member is able to create a channel 

# Expected Result
When the current user is a member, he is not allowed to create a channel. 
The channel creation button should be hidden.

# Environment
Android app
Build version: twake.2.1.2

**Comment by bobs4462** [comment]
@romanesko Can we get user permissions in /user method from proxy?

**Comment by romanesko** [comment]
Info from Romaric: **Anybody can create a channel** like in Slack, the only not allowed operation are destructive operations (reserved to admin and channel original creator).

Not an issue.
