### ISSUE TITLE
UI > On menu sidebar, it should display a workspace creation button instead of show company list button

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#208]
# Actual Result
On the menu sidebar, it's displaying a show company list button. 
The current business allows a user belongs to 1 company, that why the company list is redundant.

![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/82907940-45f5-4c79-859e-7bfd3d64d84e)

# Expected Result
If the current user is Admin or Company Owner, it should display the Workspace create button
See the design:
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/d0f34c16-319c-4546-a56e-35ec68f02fff)

**Comment by bobs4462** [comment]
@BastiaanVanGaalen We need a design for creating a new workspace, you can contact @romanesko if you need the list of fields for the creation form.

**Comment by BastiaanVanGaalen** [comment]
@romanesko would you be so kind to provide me a list of fields for a workspace creation flow.

**Comment by tlle14** [comment]
Hi @bobs4462 and @BastiaanVanGaalen 
Sorry, we need to move this ticket into the icebox column. 
We don't have a plan for implementing this feature. Let's skip this one. 

Thank you
