### ISSUE TITLE
App should have confirmation dialog before sign out

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#209]
# Actual Result
Currently, tapping to "sign out" button, the user will be logged out immediately
https://user-images.githubusercontent.com/69950655/105316656-c417b280-5bf3-11eb-9e02-0cea71be4cfc.mp4

# Expected Result
The app should have a confirmation dialog asking the user to be sure when signing out

# Environment
Android app

**Comment by bobs4462** [comment]
@BastiaanVanGaalen can you please sketch us some dialog design, before we implement this feature?

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 Of course, i will do it immediately.

**Comment by BastiaanVanGaalen** [comment]
@RockinPaul System-provided sign out views for both platforms:
https://zpl.io/bP6Ww9m

**Comment by tlle14** [comment]
@BastiaanVanGaalen @bobs4462 
Do we have a new design on zeplin? Please invite me to the team (don't be scared ;) )

**Comment by tlle14** [comment]
Thank @BastiaanVanGaalen and @RockinPaul 
Retest pass
https://images.zenhubusercontent.com/309637937/ed4d7d3c-6987-4a35-8df3-fb8e317d9891/video4391e3dd_d389_4b79_9c4e_374af533e760video.mp4
