### ISSUE TITLE
It takes time to load a warning message when opening a thread without replies

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#212]
# Actual Result
When clicking reply to the parent message without replies, it open a thread screen but takes time to load a message `No responses yet`

https://images.zenhubusercontent.com/309637937/941e6ed7-766d-4d38-b015-255cfbaa00e5/video879b4a2a_ce63_4732_a4f4_055bf5a18403video.mp4

# Expected Result
It should show the screen without latency

# Environment
Android app
Build version: twake.2.1.2

**Comment by tlle14** [comment]
This might be the same root cause with https://app.zenhub.com/workspaces/twakemobile-5fa5101d98879700119ccea9/issues/twakeapp/mobile/189

**Comment by hieuhoang998** [comment]
Hi This issue is fixed, so I close. Thank you
