### ISSUE TITLE
The message size is too small when compare with the composing text

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#221]
# Actual Result
The message size is too small when comparing with the composing text
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/e5d52dc4-ff42-40b1-9815-ed4c721f173f)

# Expected Result
The font size should be the same as in the design
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/fd395d9a-f0c0-44e9-bc99-0660fa201397)

# Environment
Android app
Build version: twake-2-2-0.

**Comment by hieuhoang998** [comment]
Hi, This issue is fixed, so I close this. Thank you
