### ISSUE TITLE
Cannot close the emoji keyboard directly

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#223]
# Actual Result
The user cannot close the Emoji Keyboard directly. He needs to back to the normal keyboard then closes by the system button

https://user-images.githubusercontent.com/69950655/105475629-25ae4e80-5cd2-11eb-94f4-5c4901764dcb.mp4

# Expected Result
The Emoji keyboard should be able to close directly by the system button. 

# Environment
Android App
Build version: twake-2-2-0

**Comment by hieuhoang998** [comment]
Hi, This issue is fixed so I close. Thank you
