### ISSUE TITLE
Thread > It doesn't display the newest message line when chatting or opening a thread.

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#224]
# Actual Result
1. When the user opens a thread, it doesn't show the newest message in a thread

https://user-images.githubusercontent.com/69950655/105480778-bd16a000-5cd8-11eb-8494-c0e98e789714.mp4

2. When the user continues sending the messages in a thread, the newest message line doesn't display. 
The screen stays in the current state.

https://user-images.githubusercontent.com/69950655/105480693-a40def00-5cd8-11eb-87c6-e30606570e4e.mp4

# Expected Result
It should always show the newest message when the user:
- Opening a thread
- Continue chatting in the thread
# Environment
Android app
Build version: twake-2-2-0

**Comment by hieuhoang998** [comment]
Hi, This issue is fixed, so I close this.
Thank you.
