### ISSUE TITLE
UI > The icons in the context menu is different with those in the design

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#225]
# Actual Result
1. The icons of reply, copy, delete, emoji button are different with the design
![image](https://user-images.githubusercontent.com/69950655/105481526-c3f1e280-5cd9-11eb-9948-79850bf34c7b.png)

2. The number of highlight emojis is 7 while the design has only 5

# Expected Result
Please confirm if we should follow the design. 
The details make it looks better
![image](https://user-images.githubusercontent.com/69950655/105481818-26e37980-5cda-11eb-84d0-d4c801c2dd57.png)

# Environment
Android App
Build version: twake-2-2-0

**Comment by bobs4462** [comment]
@BastiaanVanGaalen we are currently using material icons, and those in the mockup are custom made, should we somehow try to extract those or will you provide us with other ones?

**Comment by BastiaanVanGaalen** [comment]
@RockinPaul in case you're unable to extract them from source file, then use material set.

**Comment by BastiaanVanGaalen** [comment]
We will stay with material set for now.
