### ISSUE TITLE
Add a new feature: message editing

### ISSUE THREAD

**Issue by bobs4462** [TwakeApp/Mobile#229]
For now it will suffice to just take original message, let the user edit it as he would compose an ordinary message, and send the edited string to proxy with additional info.
Proxy endpoint:
```
PUT /messages
{
    company_id: string,
    workspace_id: string,
    channel_id: string,
    thread_id: string?
    message_id: string,
    original_str: string
}
```

**Comment by hieuhoang998** [comment]
Hi, Sometimes I can't edit the message so please check it again.
Thank you

**Comment by bobs4462** [comment]
@hieuhoang998 Hello, can you please tell us how exactly we can reproduce the issue?

**Comment by hieuhoang998** [comment]
Hi please check as flow

pre: device-Samsung A51 

1.Sign in twake app successfully

2.Select 1 people and text 

3.Press on text and check 

4.Click edit or delete or reply

Actual result: Can't edit, delete, reply

This issue occured sometimes and so it's so difficult to reproduce, please check it again. @tlle14 please confirm

**Comment by tlle14** [comment]
Thank @bobs4462 and @hieuhoang998 
The feature appears in the newest version and is under testing.
I should close this ticket.
