### ISSUE TITLE
Fix loader icon collapse when opening channel messages

### ISSUE THREAD

**Issue by bobs4462** [TwakeApp/Mobile#236]
![untitled.gif](https://images.zenhubusercontent.com/5f9ab4c67851dd4a461c956a/9208347d-2456-4b3b-8843-1d298105e3c0)

Currently it looks as it show in video, space around loader collapses, and message editing field takes up all the space

**Comment by tlle14** [comment]
Thank @RockinPaul 
Retest pass
https://images.zenhubusercontent.com/309637937/5127f15c-2b66-4b75-8396-68f470bdf041/video4477832b_91dd_4ec9_b680_837a7819a252video.mp4
