### ISSUE TITLE
UI > App icon is vertically stretched

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#25]
# Actual Result
App icon is vertically stretched
![image](https://user-images.githubusercontent.com/69950655/100979991-27cc1a80-3577-11eb-9272-7c78c818b8ca.png)

# Expected Result
The App icon should display in normal size

# Environment
Samsung A51 
Android 10
6.5 inch

**Comment by bobs4462** [comment]
Should display correctly now, on newer android devices ( > 8 ). On older devices, the issue is somewhat different, need more investigation

**Comment by tlle14** [comment]
Thanks @bobs4462 
Retest pass
![image](https://user-images.githubusercontent.com/69950655/101336397-ffad2600-38ac-11eb-9bae-58d7274142d0.png)
