### ISSUE TITLE
[Edit text] Can't edit message at the 1st time

### ISSUE THREAD

**Issue by hieuhoang998** [TwakeApp/Mobile#256]
#Precondition:
version:2.2.2 twake app
device: android: oppo reno 4
#Step
1.Open twake app
2.Log in successfully
3.Send a message ex:hello99
4.Click message then click edit
5.Input some characters example: hello99hjjjj
#Actual result: Display hello99 at the 1 st time
#Expect result: Can edit successfully
![processed (8)](https://user-images.githubusercontent.com/54783033/106716449-09df6c80-6631-11eb-8c93-131265e67624.jpeg)
![processed (7)](https://user-images.githubusercontent.com/54783033/106716460-0c41c680-6631-11eb-8415-78feef63d9be.jpeg)

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass
https://images.zenhubusercontent.com/309637937/fbd075b2-4e3c-4b4f-8f4d-c0d6c2220354/video0e3620c5_2593_4d1e_9dc6_72df8ebc81e9video.mp4

**Comment by hieuhoang998** [comment]
Hi, This issue is fixed, so I close this. Thank you
