### ISSUE TITLE
UI > Login screen UI doesn’t fit the small screen

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#26]
# Actual Result
Login screen UI doesn’t fit the 6.5 inch screen.

![image](https://user-images.githubusercontent.com/69950655/100980117-5813b900-3577-11eb-8e25-ae55f6614d32.png)

On 5 inch screen, the submit button is hidden
![image](https://user-images.githubusercontent.com/69950655/101119364-c27f3480-361d-11eb-872e-fd35589cc262.png)

# Expected Result
The screen should be responsive

# Environment
Samsung A51
Android 10
6.5 inch

**Comment by bobs4462** [comment]
Implemented text scaling, report if the issue is still there in new build

**Comment by tlle14** [comment]
The issue still happens on a 5 - 6.5 inch screen.

5-inch screen - Samsung Galaxy A5
![image](https://user-images.githubusercontent.com/69950655/101338290-5b78ae80-38af-11eb-8738-f5ce430a7eb3.png)

6.5-inch screen - Samsung A51
![image](https://user-images.githubusercontent.com/69950655/101338521-ab577580-38af-11eb-81be-4fb394a014a0.png)

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!
With 5-inch screen
![processedasdd](https://user-images.githubusercontent.com/69950655/101717061-2d72b480-3ad1-11eb-9449-342c56ef5d9a.jpeg)

With 6.5-inch screen
![1607570307646](https://user-images.githubusercontent.com/69950655/101717096-39f70d00-3ad1-11eb-891c-342e9eb8fdab.JPEG)
