### ISSUE TITLE
Message > Cannot display the file or image attached with a message

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#28]
# Precondition
On PC, attach a file with the message:
![image](https://user-images.githubusercontent.com/69950655/100980508-e7b96780-3577-11eb-90ca-8133b1495f70.png)

# Actual Result
Cannot display the file or image attached with a message on Mobile

![image](https://user-images.githubusercontent.com/69950655/100980529-f011a280-3577-11eb-86da-3cec95b81908.png)

# Expected Result
Should display a file or image attached with a message

# Environment
All mobile devices

**Comment by bobs4462** [comment]
Hello Le, it's not actually a bug, we just decided not to support files in first version of the app (neither attachment nor display).
We will make it a priority to add functionality to work with files in the next release.

**Comment by tlle14** [comment]
> Hello Le, it's not actually a bug, we just decided not to support files in first version of the app (neither attachment nor display).
> We will make it a priority to add functionality to work with files in the next release.

Thank @bobs4462
