### ISSUE TITLE
Message > Cannot react a replied message

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#29]
#  Actual Result
React a replied message on Mobile  disappears after reopen the message thread
Refer the video on https://streamable.com/n0x81d

# Steps
1. Open the thread
2. React a replied message in the thread
3. Tap Back button 2 time to go back to the channel list
4. Open the reacted replied message again
5. Verify the issue

# Expected Result
The reaction should be kept and synced to the server

# Environment
All android devices

**Comment by romanesko** [comment]
Fixed

**Comment by tlle14** [comment]
Thanks @bobs4462 
Retest pass!
https://streamable.com/9283o3
