### ISSUE TITLE
Channel > Star channel doesn’t display on the top 

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#32]
# Precondition
Mark star for some channels on PC
![image](https://user-images.githubusercontent.com/69950655/100983031-59df7b80-357b-11eb-9e86-2a6ac15dec89.png)

# Actual Result
Star channel doesn’t display on the top 
![image](https://user-images.githubusercontent.com/69950655/100983059-606df300-357b-11eb-8eb4-6ca84cfeaaa5.png)

# Expected Result
Starred channels should display on the top of the workspace
![image](https://user-images.githubusercontent.com/69950655/100983601-1f2a1300-357c-11eb-8f1f-e32f9bce2f2d.png)

# Environment
All android devices

**Comment by bobs4462** [comment]
Yes, that's intentional. Also decided to move starred channel to the next version release.
