### ISSUE TITLE
Channel > Some channels are not fully updated.

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#34]
# Actual Result
Some channels are not fully updated.

Example: 
- On FT-Mobile channel, it displays only messages are from 19 Nov – 23 Nov
![image](https://user-images.githubusercontent.com/69950655/100983946-99f32e00-357c-11eb-8ce4-d5b368e02bc5.png)

- Channel FT – SmartSla cannot display messages.
![image](https://user-images.githubusercontent.com/69950655/100983974-a5465980-357c-11eb-9c8b-30c9f176d634.png)

- FT – Twake: displays only message on 24 Nov
![image](https://user-images.githubusercontent.com/69950655/100984313-2aca0980-357d-11eb-8e0e-15d35321f16f.png)

...

# Expected Result
All channels should be up to date

# Environment
All mobile devices
Using my company account with the real data

**Comment by bobs4462** [comment]
@romanesko The bug is related to missing *userId* field in *sender* object when fetching messages. Please add some dummy id to bot users.

**Comment by romanesko** [comment]
Fake user ids added for bots

**Comment by bobs4462** [comment]
Should be fixed now

**Comment by tlle14** [comment]
Hi @bobs4462 
Retest failed!
I cannot reach the oldest message in the chat history on Mobile. Example on some channels: FT-Twake, Customer - UPN, General...

**Comment by bobs4462** [comment]
Yes the issue seems to have appeared after yesterday's refactor of proxy, looking for cause right now, should be fixed soon.

**Comment by tlle14** [comment]
Hi @bobs4462 
Retest failed
Cannot load messages in FT-SmartSla channel
![image](https://user-images.githubusercontent.com/69950655/101862342-b6a6eb80-3ba4-11eb-9a36-af084cb55d7f.png)

**Comment by tlle14** [comment]
Thanks @bobs4462 
Retest pass! 
Now we can see all the messages in all channels
