### ISSUE TITLE
Message > Cannot display quoted message

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#35]
# Precondition
Create a quoted message on PC
![image](https://user-images.githubusercontent.com/69950655/100989232-328cac80-3583-11eb-8e6a-77d5e4c6d595.png)

# Actual Result
Quoted message cannot display on Mobile
![image](https://user-images.githubusercontent.com/69950655/100989293-49cb9a00-3583-11eb-9d61-5aca9c7062bd.png)

# Expected Result
Mobile should display the quoted message

# Environment
All android devices

**Comment by romanesko** [comment]
fixed

**Comment by tlle14** [comment]
Thanks @bobs4462 

Retest pass! 
![image](https://user-images.githubusercontent.com/69950655/101148926-cd9f8800-3650-11eb-998f-ca119be39f65.png)
