### ISSUE TITLE
Channel > Displaying a channel that doesn't appear on the Web version

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#38]
# Actual Result
There's a group that doesn't have on Web version but displaying on Mobile

On Web:
![image](https://user-images.githubusercontent.com/69950655/100999210-07a85580-358f-11eb-89dd-773a91b96e23.png)

On Mobile
![image](https://user-images.githubusercontent.com/69950655/100999246-1989f880-358f-11eb-8e60-74475641281e.png)

# Expected Result
The group might be archived or deleted or be hidden...It shouldn't show on Mobile. 

# Environment
All Android devices

**Comment by bobs4462** [comment]
@romanesko it seems we are not filtering out old channels

**Comment by romanesko** [comment]
I can assume that the channel should be show in the web application… cause it has no diffs with the others:

LinShare channel:
```
{
  id: '81786684-e927-11ea-9df7-0242ac120004',
  front_id: '734bd460-1dc4-f8d6-626e-a84560759a2d',
  icon: ':moneybag:',
  name: 'LinShare',
  description: null,
  channel_group_name: null,
  private: false,
  direct: false,
  application: false,
  app_id: '',
  app_group_id: '',
  app_bot_identifier: '',
  original_workspace: 'f339d54a-e833-11ea-92c3-0242ac120004',
  original_group: '56393af2-e5fe-11e9-b894-0242ac120004',
  members_count: null,
  last_activity: 1598616647,
  connectors: [],
  tabs: [],
  messages_increment: 0,
  _user_last_message_increment: null,
  _user_last_quoted_message_id: '',
  _user_last_access: 1603981351,
  _user_muted: 0
}
```
Guild-JSandTS channel:
```
{
  id: '140cbe92-ff02-11ea-88e9-0242ac120004',
  front_id: '072a1a55-580a-c5ba-d97d-ee411cc5ed8e',
  icon: ':full_moon:',
  name: 'Guild-JSandTS',
  description: 'People willing to exchange on usage of JS technologies in our software and everywhere else',
  channel_group_name: null,
  private: false,
  direct: false,
  application: false,
  app_id: '',
  app_group_id: '',
  app_bot_identifier: '',
  original_workspace: 'f339d54a-e833-11ea-92c3-0242ac120004',
  original_group: '56393af2-e5fe-11e9-b894-0242ac120004',
  members_count: null,
  last_activity: 1601019497,
  connectors: [],
  tabs: [],
  messages_increment: 0,
  _user_last_message_increment: null,
  _user_last_quoted_message_id: '',
  _user_last_access: 1603981351,
  _user_muted: 2
}
```

**Comment by tlle14** [comment]
Hi @RomaricMourgues 
Could you help investigate why the channel isn't shown on the Web version but displays on Mobile when using the same account? Thank you.

**Comment by bobs4462** [comment]
Ping @RomaricMourgues :)

**Comment by RomaricMourgues** [comment]
Sooo this one too I will not do it because we change the channel API before the next production release :)

**Comment by bobs4462** [comment]
The issue doesn't resurface on new API

**Comment by tlle14** [comment]
Let's check when we have a database migration.
Thank @bobs4462
