### ISSUE TITLE
Channel > Displaying mixing-up messages in 2 different channels/direct

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#42]
# Actual Result
Messages in 2 channel/ direct message are displaying together in "one channel"
Refer: https://streamable.com/jl23of

# Steps 
1. Open a channel. It takes time to load. You have to leave immediately before the messages in the channel are shown.
2. Open another direct message.
3. Verify the issue

# Expected Result
The mobile app should display the correct message of the channel

# Environment
All android devices

**Comment by bobs4462** [comment]
Fixed in last PR

**Comment by tlle14** [comment]
@bobs4462  is this fix ready on the 2nd build? The test is fail

**Comment by bobs4462** [comment]
Couldn't reproduce it on the new build. Please check again, and report if the issue persists.

**Comment by tlle14** [comment]
Hi @bobs4462 
Retest failed on the 3rd build. 
https://streamable.com/13f26e

**Comment by tlle14** [comment]
Hi @bobs4462 
Retest failed on the 4th build
https://yadi.sk/i/NK2xfqzIG9ZU4g

**Comment by bobs4462** [comment]
Added extra checks for present messages in the buffer, should solve the on slow internet connections.

**Comment by tlle14** [comment]
Retest failed!
Sorry @bobs4462 
https://yadi.sk/i/nXTmA0wz6ZCHYQ

**Comment by bobs4462** [comment]
Attempt number 4 :)
Added more checks to message buffer

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!
https://streamable.com/xo2xii
