### ISSUE TITLE
App doesn't work on devices sometimes

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#47]
# Actual Result
Sometimes Twake app on my device cannot display the channels list. While another device (Xiaomi) can.
Refer https://streamable.com/m3qygt

# Expected Result
Please help investigate. The App might not compatible with the mobile device.

# Environment
Samsung A51
Android 10
Model: SM-A515F/DSN

**Comment by hantt12** [comment]
It does not only happen in Samsung A51, it happens in other devices too

**Comment by bobs4462** [comment]
That's a known issue and has to do with a weird behavior of authentication token.
If you login|use your account on twake web | desktop, and at the same time try to use the mobile version, then that's the behavior. 
For now just try to avoid using the simultaneously the same account on different platforms.
We are investigating the issue.

**Comment by bobs4462** [comment]
The JWT expiration problem was fixed on backend, the issue should be solved now

**Comment by tlle14** [comment]
Hi @bobs4462 
I don't think the issue has been fixed in this version.
![image](https://user-images.githubusercontent.com/69950655/102196029-ec740900-3ef1-11eb-8c6a-16e571999b4e.png)

**Comment by tlle14** [comment]
It seems fine.
Thank @bobs4462
