### ISSUE TITLE
Newest direct chat should be displayed on the top of the direct part

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#49]
# Actual Result
The newest direct chat (not the first time sending a message) is not jumping on the top when it has a new message.
When the user pulls to refresh the app, it still not be moved to the top.
![image](https://user-images.githubusercontent.com/69950655/101136529-0aaf4e80-3640-11eb-9526-1e10db4311ae.png)

While on Web version:
![image](https://user-images.githubusercontent.com/69950655/101135219-19950180-363e-11eb-8cf3-c824114f733f.png)

# Expected Result
When there is a new message, the direct chat should be on top of the direct (like the web version)

# Environment
All Android devices

**Comment by bobs4462** [comment]
Added direct messages sort based on their last activity

**Comment by tlle14** [comment]
Thanks @bobs4462 
Retest pass
![image](https://user-images.githubusercontent.com/69950655/101348044-997ccf00-38bd-11eb-8862-b3931917cd0e.png)
