### ISSUE TITLE
Message > Link isn't highlighted when it is selected

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#51]
# Actual Result
Link isn't highlighted when it is selected. 
This makes the User doesn't aware of which link he has already chosen
Refer https://streamable.com/nx8cuv

# Expected Result
The link should be highlighted when it is selected

# Environment
All android devices

**Comment by bobs4462** [comment]
@romanesko I can implement something like this locally, but i'm not sure that twake api allows such a thing to be persistent.

**Comment by bobs4462** [comment]
Management decided to drop this feature for indefinite time
