### ISSUE TITLE
Channel > Some channel icons cannot display on Twake mobile

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#53]
# Actual Result
Some channel icons are displaying as a question mark
![image](https://user-images.githubusercontent.com/69950655/101154504-6259b400-3658-11eb-8066-d7be8cf6191e.png)

# Expected Result
Please investigate if we can fix. 
If it depends on a mobile device, we should display the Twake icon instead of the question mark.

# Environment
All android devices

**Comment by bobs4462** [comment]
Fixed, the app will do all it can, to find the best match for saved icon

**Comment by tlle14** [comment]
Thanks, @bobs4462 
All icons are displayed well on the App.
