### ISSUE TITLE
Message > Highlighted text displays in a separated line on Mobile

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#54]
# Actual Result
A highlighted text on Mobile is displaying in a separated line.
On Mobile:
![image](https://user-images.githubusercontent.com/69950655/101157080-24f72580-365c-11eb-890c-95227ae77c14.png)

On PC:
![image](https://user-images.githubusercontent.com/69950655/101157043-17da3680-365c-11eb-9dff-f3679074d633.png)

# Expected Result
The highlighted text should display in the same line as the others

# Environment
All android devices

**Comment by bobs4462** [comment]
should be fixed now

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass
![image](https://user-images.githubusercontent.com/69950655/101435630-421f4300-393f-11eb-86e2-01136531ed81.png)
