### ISSUE TITLE
Message > a long username makes the date time displays in 2 lines

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#55]
# Actual Result
![image](https://user-images.githubusercontent.com/69950655/101159025-4e658080-365f-11eb-8b97-55c8f3f89a05.png)

# Expected result
Improve the UI

# Environment
Samsung A51
6.5-inch screen

**Comment by bobs4462** [comment]
I don't have a 6inch device/emulator, but the issue should be fixed in the next build

**Comment by tlle14** [comment]
Hi @bobs4462 
Retest failed on 5inch - 6.5inch screen

**Comment by bobs4462** [comment]
Remade the message tile a bit, it should look better now

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass! 
Great improvement
![image](https://user-images.githubusercontent.com/69950655/102478358-15320500-4090-11eb-9ab6-ed5a8b475cc7.png)
