### ISSUE TITLE
Channel > The app automatically displays a direct chat with the new user

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#57]
# Actual Result
My account suddenly displays a direct chat with a new member on Twake, that I've never intended to find/ chat with her before

# Expected Result
This is an annoying bug.
The app shouldn't show the direct chat doesn't have a chat history

# Environment
All mobile devices

**Comment by bobs4462** [comment]
I don't think that is an issue anymore

**Comment by tlle14** [comment]
Thank @bobs4462 
The issue seems to no longer happen.
