### ISSUE TITLE
Companies and Workspaces should be sorted the same order with the Web version 

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#59]
# Actual Result
The order of companies and workspaces are not similar to the Web version

On Web version:
![image](https://user-images.githubusercontent.com/69950655/101309941-2b65e700-3880-11eb-9950-d30e8e5b8328.png)

On App:
![image](https://user-images.githubusercontent.com/69950655/101310859-97e1e580-3882-11eb-8fd1-49b8077bb6dc.png)

# Expected Result
The order of Workspaces and Companies should be the same between Mobile and Web 

# Environment
All mobile devices

**Comment by bobs4462** [comment]
Done

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass

**Comment by tlle14** [comment]
Hi @bobs4462 
I saw the different order between mobile and web version for 2 channels `Frontend split` and `customer - openpaas.linagora.com`

**Comment by tlle14** [comment]
Retest pass! Thank @bobs4462 
Now a Company Owner has only 1 company
And the Workspaces have an order as on Web App.

On Mobile:
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/8a43f85e-38b8-4547-9958-7025888ee359)

On Web:
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/5f41602c-0b3f-4302-a55c-ce0777f71071)
