### ISSUE TITLE
[Story] Pinned message view in channel and direct discussion

### ISSUE THREAD

**Issue by BenoitTallandier** [TwakeApp/Mobile#590]
## User story summary
[Definition](#Definition)  
[Business case](#Business-case)  
[Criteria](#criteria)  
[UI/UX Design](#UI-UX-design)  
[Notes](#notes)  
[Related](#related)  

## Definition
```gherkin
Given I am a user
When I want to pin a message
Then I open the channel or a direct discussion
Then I long press on the message
Then I click on "PIN"
```

```gherkin
Given I am a user
When I want to see all messages that were pinned in a channel or a direct discussion
Then I open the channel or the direct discussion
Then I click on the channel header to open channel settings
Then I click on the menu "Pinned messages",
Then I can see all messages that were pinned on this channel or the direct discussion
```

## Business case
- In the pinned message list, messages are ordered by date of sending
- A pinned message has an icon in his footer in the channel / direct discussion view.
- Every member of the channel can pin/unpin/see pinned messages
- In the channel (or a direct discussion) menu, at the right of the "Pinned messages" option, I can see the number of pinned messages in the channel (or a direct discussion)
 
## UI UX Design
Final design: https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake.new?node-id=374%3A20247

## Note

**Comment by hantt12** [comment]
Hi could you please confirm this:

> In the pinned message list, messages are ordered by date

Do you date of sending the message or date of pinning the message?

**Comment by BenoitTallandier** [comment]
@hantt12  I updated the story, it is by the `date of sending`

**Comment by hantt12** [comment]
then it's not the case now. 
I sent 2 messages: message 1 and message 2
I pinned message 2
I pinned message 1
When I check the pinned list, message 2 is shown first then message 1

**Comment by hantt12** [comment]
just a small issue related to ordering at https://github.com/linagora/Twake-Mobile/issues/1366
