### ISSUE TITLE
Message > It shouldn't display the whole paragraph in a message

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#62]
# Precondition
A message is a paragraph about 22000 character length

# Actual Result
On Mobile, a long paragraph always display fully. This makes user have to infinity scroll to find other messages.
https://streamable.com/ijtno3

# Expected Result
We should have a max length for a message. 
1. If the max length is not too long, the message should be displayed fully. 
2. If the max length is too long, the long message should be displayed as a preview.

# Environment
All mobile devices

**Comment by bobs4462** [comment]
Added text collapse for long text strings.

**Comment by tlle14** [comment]
Hi @bobs4462 
Thank you for your quick fix. But this behavior we need confirmation from BA and PO. It such a new feature.

**Comment by bobs4462** [comment]
set the message shortening to 300 chars. 
We can close this issue and discuss the design related things with, well, designers :)

**Comment by tlle14** [comment]
Thank @bobs4462 
The app looks better today
