### ISSUE TITLE
Message > Copy-paste a message containing mentioned text shows the user's ID

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#63]
# Precondtion
A message has mentioned text: 
![image](https://user-images.githubusercontent.com/69950655/101345750-1f971680-38ba-11eb-9432-effbe7a05d2b.png)

# Actual Result
Copy a message then paste the clipboard, the mentioned text displays a user's ID
https://streamable.com/scw8bf

# Expected Result
It shouldn't display a user's ID. 
The mentioned text should display correctly

# Environment
All android devices

**Comment by bobs4462** [comment]
@romanesko What can we do about this bug, is it possible to cut out userid from original_str using some regexes?

**Comment by bobs4462** [comment]
@tlle14 is there any problem with this issue, it seems to be stuck in review for a while now...

**Comment by tlle14** [comment]
Hi @bobs4462 
It's because of this issue: https://github.com/TwakeApp/Mobile/issues/175

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass
https://images.zenhubusercontent.com/309637937/d426112e-22d0-4cdc-bbba-fe071dff1a22/video681e82fd_2802_4805_aa22_176d38f6e474video.mp4
