### ISSUE TITLE
Login screen flash displays when opening the app

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#64]
# Actual Result
After a long time opens the app, the login screen flashly display then redirects to the workspace.
https://streamable.com/wzv7yu

# Expected Result
The login screen shouldn't display when the user is still logged in to the app. 

# Environment
All android devices

**Comment by bobs4462** [comment]
Yes, we'll replace it with splashscreen

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!
https://images.zenhubusercontent.com/309637937/d56034ef-b223-421e-ac27-5fde6db92dfb/video84ff0783_edc3_45c5_be68_6ee66869be20video.mp4
