### ISSUE TITLE
Message > Incorrect behavior after deleting a message

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#65]
# Precondition
Message1: a message without response
Message2: a child message as a response in a parent message
Message3: a parent message (with >= 1 response)

# Actual Result

When deleting Message1 => it displays a grey screen with a `reply` popup/button
https://streamable.com/rcxqse

When deleting Message2 => Message2 doesn't disappear. The user has to refresh the app manually
https://streamable.com/kkkf23

When deleting Message3 => Message3 disappears immediately but after refreshing the app, it displays again.
https://streamable.com/sx9nlr

# Expected Result
When deleting a message, the message should disappear immediately.
The message with or without a response should able to be deleted. 

# Environment
All mobile devices

**Comment by bobs4462** [comment]
Fixed first and second behavior, but the third behavior is somewhat expected, as twake doesn't allow to delete messages which has responses, maybe we should just remove the option to delete messages which has more than 0 responses....

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!
- issue 1&2 are fixed 
- Issue 3 is improved. The user is no longer able to open a new message as a thread. He must use the context menu.
