### ISSUE TITLE
Message > Able to open a message without a response as a thread

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#66]
# Actual Result
A message without a response will not be opened as a thread.
But a new message that already is submitted able to be opened as a thread.
https://streamable.com/ncsylz

# Expected Result
Please confirm the expected behavior: if a message without response is able to open in a thread screen.

# Environment
All Android devices

**Comment by bobs4462** [comment]
Well, originally I designed it in such a way, that if message has no responses already, you have to initiate thread via context menu, clicking on reply option. But the behavior when newly posted message can be clicked to open a thread seems to be a bug. Will check it out.

**Comment by bobs4462** [comment]
Added check for new messages, so you cannot create thread without context menu

**Comment by tlle14** [comment]
Retest pass! 
Thank @bobs4462
