### ISSUE TITLE
No Validation for Login form

### ISSUE THREAD

**Issue by hantt12** [TwakeApp/Mobile#72]
When I try to login with incorrect information, error message should be shown

- Incorrect username
- Incorrect password

Currently there is no error message

**Comment by bobs4462** [comment]
we cannot differentiate between incorrect password or username, we can only show some info saying that we cannot login with given credentials

**Comment by hantt12** [comment]
It's ok. Let's do it

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!
![image](https://user-images.githubusercontent.com/69950655/101856063-2ada9280-3b97-11eb-93ad-2b3ddea822dd.png)
