### ISSUE TITLE
A message sent from mobile cannot display on the old Twake app on iOS

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#78]
# Actual Result
A message sent from mobile cannot display on the old Twake app on iOS
![image](https://user-images.githubusercontent.com/69950655/101718837-9e679b80-3ad4-11eb-9420-8251651ceeaa.png)

# Expected result
The message should display normally for the old Twake app. 

# Environment
All Android devices
Old Twake app on iOS

**Comment by romanesko** [comment]
It won't be fixed

**Comment by tlle14** [comment]
@romanesko I know the current ios app will be replaced by the Flutter one. 
But we should fix it in case the user still uses the old app. Could you confirm?

**Comment by tlle14** [comment]
And @romanesko please assign the issue to me if you think it is not a bug. I will close it.

**Comment by romanesko** [comment]
The api will be changed anyway, so the old version won't work. Everybody will have to update the app anyway.

**Comment by bobs4462** [comment]
I think we can close the issue, as the old api will be deprecated soon.
