### ISSUE TITLE
A message sent from Mobile cannot display instantly on Web version 

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#79]
# Actual Result
Sending a message from mobile to the Web user, the message doesn't display instantly. The user needs to refresh the app to see.

# Expected Result
The message should display instantly on the Web version

# Environment
All mobile devices

**Comment by romanesko** [comment]
It's common API problem, should be solved with new API version, nothing can do here (can be closed)

**Comment by tlle14** [comment]
Thanks @romanesko 
Tell me when it's ready

**Comment by tlle14** [comment]
Sorry @romanesko 
My mistake when closing this issue (That I don't remember why). 
Please keep working on this.

**Comment by tlle14** [comment]
Retest pass!
Thank @bobs4462
