### ISSUE TITLE
Login > Error message displays in the breaking lines on small screen

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#81]
# Actual Result
The error message is displaying in the breaking lines on the small screen (6.5 inch), which is not a good UI
![image](https://user-images.githubusercontent.com/69950655/101856245-7c831d00-3b97-11eb-817d-0dd8f2cfbd29.png)

# Expected result
On the small screen, the message should display in only a line. 
We should replace by a shorter message.

**Comment by bobs4462** [comment]
Shortened the message

**Comment by tlle14** [comment]
Thank @bobs4462 
One more request, could you make the message aligned to the center?
![image](https://user-images.githubusercontent.com/69950655/102199247-fa2b8d80-3ef5-11eb-90af-3e4c11dbdfd2.png)

**Comment by bobs4462** [comment]
Centered

**Comment by tlle14** [comment]
Retest pass!
Thank @bobs4462 
![image](https://user-images.githubusercontent.com/69950655/102305175-dfa6f200-3f91-11eb-875d-424f256aa078.png)
