### ISSUE TITLE
The App font size and style should be optimized

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#82]
# Actual Result
1. The font size is too big, that makes:
- A long channel name or a long username cannot display fully on the narrow screen
- A message looks longer with the big font size

2. There are too many font styles (different style, size, color) on a screen. That makes the app looks more complex

# Expected Result
1. App font size should be decreased. 
2. Date-time and additional information should be in the same font style and size
The channel name and username should be in the same font

We need help from the UI/UX designer.

**Comment by bobs4462** [comment]
We are currently reviewing all styles with designer. For now I've rewrote the calculating of text size multipliers based on screen size. Should help

**Comment by tlle14** [comment]
Thank @bobs4462 and the Designer, the app looks better.
