### ISSUE TITLE
Message > A message from Bot displays the incorrect format

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#83]
# Actual result
1. Displaying a preview message instead of the bot name.
2. Link in the bot message isn't highlighted

On mobile:
![image](https://user-images.githubusercontent.com/69950655/101864506-c1628000-3ba6-11eb-8f9c-24509661f9a6.png)

On PC:
![image](https://user-images.githubusercontent.com/69950655/101864774-2ddd7f00-3ba7-11eb-9ac3-f2f37a724117.png)

# Expected Result
Should display the message in the format on Web version

**Comment by romanesko** [comment]
| before | after |
|---|---|
| <img width="320" alt="Снимок экрана 2020-12-23 в 16 25 52" src="https://user-images.githubusercontent.com/1404610/103000835-dcd17180-453c-11eb-87bf-40c0195560dc.png"> | <img width="320" alt="Снимок экрана 2020-12-23 в 16 34 07" src="https://user-images.githubusercontent.com/1404610/103000840-dfcc6200-453c-11eb-9630-7c7355a988aa.png"> |

P.S. for now we can't determine Bot's name in current API, waiting for new one to solve this

**Comment by tlle14** [comment]
Thank @romanesko 
Retest pass!
I can see a better UI for the bot message.
