### ISSUE TITLE
Thread > The header of the thread screen should be simplified

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#84]
# Actual Result
With a long channel name, the header tab of the thread screen looks untidy
![image](https://user-images.githubusercontent.com/69950655/101877902-4bb7dd80-3bc1-11eb-9513-c480259843b9.png)

# Expected Result
The header tab should be simplified, like the one on the current Twake mobile
![image](https://user-images.githubusercontent.com/69950655/101878419-1e1f6400-3bc2-11eb-8338-9ec8cea95c7d.png)

# Environment

**Comment by bobs4462** [comment]
Little cosmetic fixes recomended by our designer.

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass
![image](https://user-images.githubusercontent.com/69950655/102479359-61317980-4091-11eb-9b53-9229f38c1aae.png)
