### ISSUE TITLE
Mesage > The Smile icon on Web version displays as a Sad icon on Mobile

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#85]
# Actual Result
Icon displays incorrectly on Mobile

On the Web:
![image](https://user-images.githubusercontent.com/69950655/101879061-4b204680-3bc3-11eb-820b-e707c8e14fe6.png)

On the mobile
![image](https://user-images.githubusercontent.com/69950655/101879093-5a9f8f80-3bc3-11eb-8f17-a72a11300b20.png)

# Expected Result
Icons should display correctly

# Environment
Build version 1.5
All android devices

**Comment by bobs4462** [comment]
There's a discrepancy between emoji used on web, and those used in app. The issue is fixed with temporary workaround. Will talk to Romaric to sync emoji collections.

**Comment by bobs4462** [comment]
Issue is fixed completely.

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!

Finally, I see that smile on Mobile:
![image](https://user-images.githubusercontent.com/69950655/102196624-bb480880-3ef2-11eb-8384-c55bf184750c.png)

On Web: 
![image](https://user-images.githubusercontent.com/69950655/102196680-ce5ad880-3ef2-11eb-9cb0-4f06f4823214.png)
