### ISSUE TITLE
Message > Manipulating with the context menu duplicate the message contains a line break

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#87]
# Precondition
A message contains a line break

# Actual result
Tap to the message to manipulate with the context menu makes the message duplicated
https://yadi.sk/i/Lc8H5cKXPjlo7g

# Steps
1. Copy the message contains a line break
2. Select the reply text field
3. Verify the issue

# Expected result
Please remove the duplicated line when manipulating with the context menu

**Comment by bobs4462** [comment]
That's ... pretty unexpected bug :)

**Comment by bobs4462** [comment]
Couldn't reproduce the issue after some bugfixes. Might have inadvertently fixed the thing without knowing :D

**Comment by tlle14** [comment]
Hi @bobs4462 
Unfortunately, the issue becomes worse. You can easily reproduce by open a thread then back to the direct chat or channel, messages contain a line break will be duplicated
https://streamable.com/9uj3k6

**Comment by bobs4462** [comment]
Fixed, was related to message collapsing

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass! There's no more duplicated
