### ISSUE TITLE
Message > Cannot un-react from Mobile

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#88]
# Precondition
A message has a reaction

# Actual Result
From mobile, unreacted isn't successful
https://yadi.sk/i/G13KNXTh3QVV7g

# Environment
Version 1.5

**Comment by bobs4462** [comment]
Fixed the issue, "unreaction" should work now

**Comment by tlle14** [comment]
Hi @bobs4462 
Retest pass when un-react with a parent message. 
But failed to unreacted a response
https://streamable.com/1183yq

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!
https://streamable.com/47xlk0
