### ISSUE TITLE
Message > A message contains more than 4 reaction icons will hide the link "see all answers"

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#89]
# Actual Result
In a narrow screen, if the message has more than 4 reaction icons, the "see all answers" link will be hidden
![image](https://user-images.githubusercontent.com/69950655/101897493-3650ac80-3bdd-11eb-8324-ab66e23091e5.png)

# Expected Result
The `see all answers` should display in another line

# Environment
Samsung A51, 6.5-inch screen

**Comment by bobs4462** [comment]
Fixed the element wrapping, now if now more space is available, it will jump to the next line

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!
![image](https://user-images.githubusercontent.com/69950655/102476960-545f5680-408e-11eb-9408-161815523b6b.png)
