### ISSUE TITLE
Message > Incorrectly display a line break when message contains a link

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#90]
# Precondtion
A message contains a link before a line break
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua https://loremipsum.io/generator/?n=30&t=p
Tempus egestas sed sed risus pretium. Aenean et tortor at risus viverra adipiscing at in tellus. Eu lobortis elementum nibh tellus molestie nunc non blandit.
```

# Actual Result
1. A message contains a link will make a line break before the link. After the link, the line break doesn't display.
On PC:
![image](https://user-images.githubusercontent.com/69950655/101899327-3900d100-3be0-11eb-8187-73edb8fb5aa3.png)

On Mobile:
![image](https://user-images.githubusercontent.com/69950655/101899577-a14fb280-3be0-11eb-9367-3a9f9584e655.png)

2. When there have some links on a message, the message will display a lot of `show more` buttons
![image](https://user-images.githubusercontent.com/69950655/101903540-027a8480-3be7-11eb-8589-59d3a29b1f47.png)

# Expected result
Should be careful with a link in a message. 
Shouldn't have a line break before a link. 
one message should have only one `show more` button

# Environment
All android devices

**Comment by bobs4462** [comment]
@romanesko we have to discuss this issue

**Comment by bobs4462** [comment]
Completely overhauled messages collapse, the issue shouldn't be there anymore

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!

![image](https://user-images.githubusercontent.com/69950655/102317189-b2fed480-3fa9-11eb-9c01-9c2bb2f2ac2a.png)
![image](https://user-images.githubusercontent.com/69950655/102317533-42a48300-3faa-11eb-8297-9a5a98dda814.png)
