### ISSUE TITLE
Message > Always display a three dots before "show less" button

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#92]
# Precondition
A message is long

# Actual Result
![image](https://user-images.githubusercontent.com/69950655/101900444-140d5d80-3be2-11eb-9d47-7151b5aea87f.png)

# Expected Result
`Show less` button should be in another line
Shouldn't have three dots before `show less` button.

**Comment by bobs4462** [comment]
Moved show less to new line, removed three dots

**Comment by tlle14** [comment]
Thank @bobs4462 

Retest pass
![Uploading image.png…]()
