### ISSUE TITLE
Thread > Displaying maximum 10 responses in a thread

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#93]
# Preconditon
A message has more than 10 responses

# Actual Result
Mobile can only display a maximum 10 responses, cannot load more
![image](https://user-images.githubusercontent.com/69950655/101904349-4621be00-3be8-11eb-9d85-77587cbbce66.png)

# Expected result
It should be able to show load all responses

**Comment by romanesko** [comment]
proxy returns all of them. gonna look into app

**Comment by bobs4462** [comment]
The issue was, that we requested responses with their respective threads (bundled together). 
Fixed the issue by requesting each thread's responses separately

**Comment by tlle14** [comment]
Hi @bobs4462 
It seems able to load maximum 50 responses.
Expected result: It should be able to load all responses

**Comment by bobs4462** [comment]
Set limit to 1000

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!
